package ch.pontius.kiar.utilities

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import java.io.IOException
import java.net.URL

/**
 * Utility class to perform geocoding.
 *
 * @see https://nominatim.org/release-docs/develop/api/Reverse/
 *
 * @author Ralph Gasser
 * @version 1.0.0
 */
object Geocoding {

    /** The [Json] parser used by [Geocoding]. */
    private val json = Json { ignoreUnknownKeys = true }

    /**
     * Attempts geocoding to obtain coordinates for the provided address.
     *
     * @param address The address to obtain coordinates for.
     * @return [GeocodingResponse]
     */
    fun geocode(address: String): GeocodingResponse? = try {
        /** Reads the search pattern from the parameters map.*/
        val url: URL = URL("https://nominatim.openstreetmap.org/search?q=${address}&format=json")
        val connection = url.openConnection()
        val response = connection.inputStream.use {
            this.json.decodeFromStream<List<GeocodingResponse>>(it)
        }
        response.firstOrNull()
    } catch (e: IOException) {
        null
    }


    /**
     * A response as generated by the [Geocoding] class.
     */
    @Serializable
    data class GeocodingResponse(val display_name: String, val lat: Float, val lon: Float, val type: String)
}