package ch.pontius.kiar.utilities

import io.github.oshai.kotlinlogging.KLogger
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import java.net.HttpURLConnection
import java.net.URL

/** The [KLogger] instance for [Geocoding]. */
private val logger: KLogger = KotlinLogging.logger {}

/**
 * Utility class to perform geocoding.
 *
 * @see https://nominatim.org/release-docs/develop/api/Reverse/
 *
 * @author Ralph Gasser
 * @version 1.0.1
 */
object Geocoding {

    /** The [Json] parser used by [Geocoding]. */
    private val JSON = Json { ignoreUnknownKeys = true }

    /**
     * Attempts geocoding to obtain coordinates for the provided address.
     *
     * @param address The address to obtain coordinates for.
     * @return [GeocodingResponse]
     */
    fun geocode(street: String?, city: String, zip: Int): GeocodingResponse? = try {
        /** Reads the search pattern from the parameters map.*/
        val url: URL = if (street != null) {
            URL("https://nominatim.openstreetmap.org/search?street=${street.replace(' ', '+')}&city=${city.replace(' ', '+')}&postalcode=$zip&format=json&limit=1&email=info@kimnet.ch")
        } else {
            URL("https://nominatim.openstreetmap.org/search?city=${city.replace(' ', '+')}&postalcode=$zip&format=json&limit=1&email=info@kimnet.ch")
        }
        val connection = url.openConnection() as HttpURLConnection
        connection.setRequestMethod("GET")
        connection.setRequestProperty("User-Agent", "Mozilla/5.0 (compatible; Kiar/1.0.0; +https://www.kimnet.ch)")
        if (connection.getResponseCode() != 200) {
            logger.error { "Failed to generate coordinates from address: HTTP Status Code ${connection.getResponseCode()}" }
            null
        } else {
            val response = connection.inputStream.use {
                this.JSON.decodeFromStream<List<GeocodingResponse>>(it)
            }
            response.firstOrNull()
        }
    } catch (e: Throwable) {
        logger.error(e) { "Failed to generate coordinates from address." }
        null
    }

    /**
     * A response as generated by the [Geocoding] class.
     */
    @Serializable
    data class GeocodingResponse(val display_name: String, val lat: Float, val lon: Float, val type: String)
}