# Dependency versions
bcryptVersion=0.4
caffeineVersion=3.2.4
commonsImagingVersion=1.0.0-alpha6
exposedVersion=1.5.0
gsonVersion=2.14.0
ktorVersion=3.5.2
jsonPathVersion=3.0.0
junitVersion=5.14.1
kotlinVersion=2.4.20
kotlinCoroutines=1.11.0
kotlinLoggingVersion=8.0.4
kotlinSerialization=1.11.0
log4jVersion=2.26.1
poiVersion=5.5.1
scrimageVersion=4.6.8
slf4jVersion=2.0.19
solrjVersion=10.0.0
sqliteVersion=3.53.4.0

# Codestyle settings
kotlin.code.style=official