/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageDeployment } from './imageDeployment';
import { ApacheSolrCollection } from './apacheSolrCollection';


export interface ApacheSolrConfig { 
    id?: string | null;
    name: string;
    description?: string | null;
    server: string;
    publicServer?: string | null;
    username?: string | null;
    password?: string | null;
    createdAt?: number | null;
    changedAt?: number | null;
    collections: Array<ApacheSolrCollection>;
    deployments: Array<ImageDeployment>;
}

