/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionType } from './collectionType';


export interface ApacheSolrCollection { 
    name: string;
    type: CollectionType;
    selector?: string;
    deleteBeforeImport: boolean;
    acceptEmptyFilter: boolean;
    match: boolean;
}
export namespace ApacheSolrCollection {
}


