/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Canton = {
    AG: 'AG',
    BE: 'BE',
    BL: 'BL',
    BS: 'BS',
    LU: 'LU',
    SO: 'SO'
} as const;
export type Canton = typeof Canton[keyof typeof Canton];

