/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CollectionType = 'OBJECT' | 'PERSON' | 'MUSEUM' | 'COLLECTION';

export const CollectionType = {
    OBJECT: 'OBJECT' as CollectionType,
    PERSON: 'PERSON' as CollectionType,
    MUSEUM: 'MUSEUM' as CollectionType,
    COLLECTION: 'COLLECTION' as CollectionType
};

