/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MappingFormat } from './mappingFormat';
import { AttributeMapping } from './attributeMapping';


export interface EntityMapping { 
    id?: string | null;
    name: string;
    description?: string | null;
    type: MappingFormat;
    createdAt?: number | null;
    changedAt?: number | null;
    attributes: Array<AttributeMapping>;
}
export namespace EntityMapping {
}


