/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ImageFormat = 'JPEG' | 'PNG';

export const ImageFormat = {
    JPEG: 'JPEG' as ImageFormat,
    PNG: 'PNG' as ImageFormat
};

