/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ImageFormat} from './imageFormat';


export interface ImageDeployment { 
    id?: number | null;
    name: string;
    format: ImageFormat;
    source: string;
    path: string;
    server?: string | null;
    maxSize: number;
}
export namespace ImageDeployment {
}


