/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ImageFormat = {
    JPEG: 'JPEG',
    PNG: 'PNG'
} as const;
export type ImageFormat = typeof ImageFormat[keyof typeof ImageFormat];

