/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ImageFormat = 'JPEG' | 'PNG';

export const ImageFormat = {
    JPEG: 'JPEG' as ImageFormat,
    PNG: 'PNG' as ImageFormat
};

