/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Institution { 
    id?: string | null;
    name: string;
    displayName: string;
    participantName: string;
    description?: string | null;
    isil?: string | null;
    street?: string | null;
    zip: number;
    city: string;
    canton: string;
    longitude?: number | null;
    latitude?: number | null;
    email: string;
    homepage?: string | null;
    publish: boolean;
    availableCollections: Array<string>;
    selectedCollections: Array<string>;
    defaultRightStatement?: string | null;
    defaultCopyright?: string | null;
    defaultObjectUrl?: string | null;
    imageName?: string | null;
    createdAt?: number | null;
    changedAt?: number | null;
}

