/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobStatus } from './jobStatus';
import { JobSource } from './jobSource';


export interface Job { 
    id?: string;
    name: string;
    status: JobStatus;
    source: JobSource;
    templateName?: string;
    createdAt: number;
    createdBy: string;
}
export namespace Job {
}


