/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobLogLevel = 'WARNING' | 'ERROR' | 'VALIDATION' | 'SEVERE';

export const JobLogLevel = {
    WARNING: 'WARNING' as JobLogLevel,
    ERROR: 'ERROR' as JobLogLevel,
    VALIDATION: 'VALIDATION' as JobLogLevel,
    SEVERE: 'SEVERE' as JobLogLevel
};

