/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JobSource = {
    WATCHER: 'WATCHER',
    WEB: 'WEB'
} as const;
export type JobSource = typeof JobSource[keyof typeof JobSource];

