/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobSource = 'WATCHER' | 'WEB';

export const JobSource = {
    WATCHER: 'WATCHER' as JobSource,
    WEB: 'WEB' as JobSource
};

