/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JobStatus = {
    CREATED: 'CREATED',
    ABORTED: 'ABORTED',
    HARVESTED: 'HARVESTED',
    RUNNING: 'RUNNING',
    SCHEDULED: 'SCHEDULED',
    INTERRUPTED: 'INTERRUPTED',
    INGESTED: 'INGESTED',
    FAILED: 'FAILED'
} as const;
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];

