/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobStatus = 'CREATED' | 'ABORTED' | 'HARVESTED' | 'RUNNING' | 'SCHEDULED' | 'INTERRUPTED' | 'INGESTED' | 'FAILED';

export const JobStatus = {
    CREATED: 'CREATED' as JobStatus,
    ABORTED: 'ABORTED' as JobStatus,
    HARVESTED: 'HARVESTED' as JobStatus,
    RUNNING: 'RUNNING' as JobStatus,
    SCHEDULED: 'SCHEDULED' as JobStatus,
    INTERRUPTED: 'INTERRUPTED' as JobStatus,
    INGESTED: 'INGESTED' as JobStatus,
    FAILED: 'FAILED' as JobStatus
};

