/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobType = 'XML' | 'JSON' | 'KIAR';

export const JobType = {
    XML: 'XML' as JobType,
    JSON: 'JSON' as JobType,
    KIAR: 'KIAR' as JobType
};

