/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type JobType = 'XML' | 'JSON' | 'EXCEL' | 'KIAR';

export const JobType = {
    XML: 'XML' as JobType,
    JSON: 'JSON' as JobType,
    EXCEL: 'EXCEL' as JobType,
    KIAR: 'KIAR' as JobType
};

