/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const JobType = {
    XML: 'XML',
    JSON: 'JSON',
    EXCEL: 'EXCEL',
    KIAR: 'KIAR'
} as const;
export type JobType = typeof JobType[keyof typeof JobType];

