/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const MappingFormat = {
    XML: 'XML',
    JSON: 'JSON',
    EXCEL: 'EXCEL'
} as const;
export type MappingFormat = typeof MappingFormat[keyof typeof MappingFormat];

