/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MappingFormat = 'XML' | 'JSON' | 'EXCEL';

export const MappingFormat = {
    XML: 'XML' as MappingFormat,
    JSON: 'JSON' as MappingFormat,
    EXCEL: 'EXCEL' as MappingFormat
};

