/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Institution} from './institution';


export interface ObjectCollection { 
    id?: number | null;
    uuid?: string | null;
    name: string;
    displayName: string;
    publish: boolean;
    description: string;
    institution?: Institution;
    filters: Array<string>;
    images: Array<string>;
    createdAt?: number | null;
    changedAt?: number | null;
}

