/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Role = 'ADMINISTRATOR' | 'MANAGER' | 'VIEWER';

export const Role = {
    ADMINISTRATOR: 'ADMINISTRATOR' as Role,
    MANAGER: 'MANAGER' as Role,
    VIEWER: 'VIEWER' as Role
};

