/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Role = {
    ADMINISTRATOR: 'ADMINISTRATOR',
    MANAGER: 'MANAGER',
    VIEWER: 'VIEWER'
} as const;
export type Role = typeof Role[keyof typeof Role];

