/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformerType } from './transformerType';


export interface TransformerConfig { 
    type: TransformerType;
    parameters: { [key: string]: string; };
}
export namespace TransformerConfig {
}


