/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransformerType = 'DISPLAY' | 'SYSTEM' | 'RIGHTS';

export const TransformerType = {
    DISPLAY: 'DISPLAY' as TransformerType,
    SYSTEM: 'SYSTEM' as TransformerType,
    RIGHTS: 'RIGHTS' as TransformerType
};

