/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Role} from './role';
import {Institution} from './institution';


export interface User { 
    id?: number | null;
    username: string;
    password?: string | null;
    email?: string | null;
    active: boolean;
    role: Role;
    institution?: Institution;
    createdAt: number;
    changedAt: number;
}
export namespace User {
}


