/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ValueParser = {
    UUID: 'UUID',
    STRING: 'STRING',
    MULTISTRING: 'MULTISTRING',
    DATE: 'DATE',
    INTEGER: 'INTEGER',
    DOUBLE: 'DOUBLE',
    COORD_WGS84: 'COORD_WGS84',
    COORD_LV95: 'COORD_LV95',
    IMAGE_FILE: 'IMAGE_FILE',
    IMAGE_MPLUS: 'IMAGE_MPLUS'
} as const;
export type ValueParser = typeof ValueParser[keyof typeof ValueParser];

