/**
 * KIAR Dashboard API
 * API for the KIAR Dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ValueParser = 'UUID' | 'STRING' | 'MULTISTRING' | 'DATE' | 'INTEGER' | 'DOUBLE' | 'COORD_WGS84' | 'COORD_LV95' | 'IMAGE_FILE' | 'IMAGE_MPLUS';

export const ValueParser = {
    UUID: 'UUID' as ValueParser,
    STRING: 'STRING' as ValueParser,
    MULTISTRING: 'MULTISTRING' as ValueParser,
    DATE: 'DATE' as ValueParser,
    INTEGER: 'INTEGER' as ValueParser,
    DOUBLE: 'DOUBLE' as ValueParser,
    COORD_WGS84: 'COORD_WGS84' as ValueParser,
    COORD_LV95: 'COORD_LV95' as ValueParser,
    IMAGE_FILE: 'IMAGE_FILE' as ValueParser,
    IMAGE_MPLUS: 'IMAGE_MPLUS' as ValueParser
};

