export * from './apacheSolr.service';
import { ApacheSolrService } from './apacheSolr.service';
export * from './config.service';
import { ConfigService } from './config.service';
export * from './entityMapping.service';
import { EntityMappingService } from './entityMapping.service';
export * from './institution.service';
import { InstitutionService } from './institution.service';
export * from './job.service';
import { JobService } from './job.service';
export * from './jobTemplate.service';
import { JobTemplateService } from './jobTemplate.service';
export * from './masterdata.service';
import { MasterdataService } from './masterdata.service';
export * from './oAI.service';
import { OAIService } from './oAI.service';
export * from './participant.service';
import { ParticipantService } from './participant.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './transformer.service';
import { TransformerService } from './transformer.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ApacheSolrService, ConfigService, EntityMappingService, InstitutionService, JobService, JobTemplateService, MasterdataService, OAIService, ParticipantService, SessionService, TransformerService, UserService];
