export * from './apacheSolr.service';
import {ApacheSolrService} from './apacheSolr.service';
import {CollectionService} from './collection.service';
import {ConfigService} from './config.service';
import {EntityMappingService} from './entityMapping.service';
import {InstitutionService} from './institution.service';
import {JobService} from './job.service';
import {JobTemplateService} from './jobTemplate.service';
import {MasterdataService} from './masterdata.service';
import {OAIService} from './oAI.service';
import {ParticipantService} from './participant.service';
import {SessionService} from './session.service';
import {UserService} from './user.service';

export * from './collection.service';
export * from './config.service';
export * from './entityMapping.service';
export * from './institution.service';
export * from './job.service';
export * from './jobTemplate.service';
export * from './masterdata.service';
export * from './oAI.service';
export * from './participant.service';
export * from './session.service';
export * from './user.service';
export const APIS = [ApacheSolrService, CollectionService, ConfigService, EntityMappingService, InstitutionService, JobService, JobTemplateService, MasterdataService, OAIService, ParticipantService, SessionService, UserService];
