/**
 * KIAR Dashboard API
 *
 * Contact: support@kimnet.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';


// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class OAIService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * An endpoint that provides OAI-PMH harvesting for the specified collection.
     * @param collection The collection to harvest.
     * @param verb The OAI-PMH verb.
     * @param identifier The identifier to harvest (used for GetRecord ).
     * @param resumptionToken The OAI-PMH resumption token (used for ListIdentifiers and ListRecords).
     * @param metadataPrefix The OAI-PMH metadata prefix (used for GetRecord, ListIdentifiers and ListRecords).
     * @param set The OAI-PMH set criterion for selective harvesting (used for ListIdentifiers and ListRecords).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOaiPmh(collection: string, verb: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public getOaiPmh(collection: string, verb: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public getOaiPmh(collection: string, verb: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public getOaiPmh(collection: string, verb: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (collection === null || collection === undefined) {
            throw new Error('Required parameter collection was null or undefined when calling getOaiPmh.');
        }
        if (verb === null || verb === undefined) {
            throw new Error('Required parameter verb was null or undefined when calling getOaiPmh.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>verb, 'verb');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>identifier, 'identifier');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>resumptionToken, 'resumptionToken');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>metadataPrefix, 'metadataPrefix');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>set, 'set');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/xml'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/${this.configuration.encodeParam({name: "collection", value: collection, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/oai-pmh`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * An endpoint that provides OAI-PMH harvesting for the specified collection.
     * @param collection The collection to harvest.
     * @param verb 
     * @param identifier 
     * @param resumptionToken 
     * @param metadataPrefix 
     * @param set 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postOaiPmh(collection: string, verb?: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public postOaiPmh(collection: string, verb?: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public postOaiPmh(collection: string, verb?: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public postOaiPmh(collection: string, verb?: string, identifier?: string, resumptionToken?: string, metadataPrefix?: string, set?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/xml', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (collection === null || collection === undefined) {
            throw new Error('Required parameter collection was null or undefined when calling postOaiPmh.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/xml'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (verb !== undefined) {
            localVarFormParams = localVarFormParams.append('verb', <any>verb) as any || localVarFormParams;
        }
        if (identifier !== undefined) {
            localVarFormParams = localVarFormParams.append('identifier', <any>identifier) as any || localVarFormParams;
        }
        if (resumptionToken !== undefined) {
            localVarFormParams = localVarFormParams.append('resumptionToken', <any>resumptionToken) as any || localVarFormParams;
        }
        if (metadataPrefix !== undefined) {
            localVarFormParams = localVarFormParams.append('metadataPrefix', <any>metadataPrefix) as any || localVarFormParams;
        }
        if (set !== undefined) {
            localVarFormParams = localVarFormParams.append('set', <any>set) as any || localVarFormParams;
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/${this.configuration.encodeParam({name: "collection", value: collection, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/oai-pmh`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
